name: CI

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build project
        run: |
          cd build
          make all
      - name: Run tests
        run: |
          cd build
          ./fakeit_tests.exe
  clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build project
        run: |
          cd build
          make -f clang_makefile all
      - name: Run tests
        run: |
          cd build
          ./fakeit_tests.exe
